### ISSUE TITLE
error_description="Didn't find publicKey for specified kid"

### ISSUE THREAD

**Issue by mightyhorst** [ivangfr/springboot-keycloak-openldap#3]
For Bill Gates example, when POSTing to the private endpoint 
`curl -i -H "Authorization: Bearer $BGATES_ACCESS_TOKEN" http://localhost:$PORT/api/private`

where $BGATES_ACCESS_TOKEN decoded is:
```javascript
{
  "jti": "ffa73f05-4109-4a90-926a-ed7013278144",
  "exp": 1551843672,
  "nbf": 0,
  "iat": 1551843372,
  "iss": "http://localhost:8181/auth/realms/company-services",
  "aud": "account",
  "sub": "42e8dcf1-d1e1-4f65-b5d5-ef46180f8c6e",
  "typ": "Bearer",
  "azp": "simple-service",
  "auth_time": 0,
  "session_state": "57df6580-603a-4ac9-ba4c-2bb1864c15ad",
  "acr": "1",
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    },
    "simple-service": {
      "roles": [
        "user"
      ]
    }
  },
  "scope": "profile email",
  "email_verified": false,
  "name": "Bill Gates gates",
  "preferred_username": "bgates",
  "given_name": "Bill Gates",
  "family_name": "gates"
}
```

The result of the curl request is

```
HTTP/1.1 401 
WWW-Authenticate: Bearer realm="company-services", error="invalid_token", error_description="Didn't find publicKey for specified kid"
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
WWW-Authenticate: Bearer realm="company-services", error="invalid_token", error_description="Didn't find publicKey for specified kid"
Content-Length: 0
Date: Wed, 06 Mar 2019 03:31:13 GMT
```

Is this something to do with a missing public key? 

I am running the Sprint Boop app inside a docker container like so: 
```bash
FROM openjdk:8-jdk-alpine

COPY . .

EXPOSE 8080

CMD ./mvnw clean spring-boot:run
```

then I build and run it with `docker build -t springboot . && docker run -p $PORT:8080 springboot`

**Comment by ivangfr** [comment]
Hey Nick,

It is happening due to a couple of reasons:
- the `springboot` app running in a docker container cannot see Keycloak at `http://localhost:8181`.
- when you get a JWT token and inform it to a service secured by Keycloak, the _KEYCLOAK URL_ must be the same, i.e, the token cannot have an `iss` `http://localhost:8181/auth` and the `keycloak_url` in the service something like `http://keycloak:8080/auth`.

What you can do is:

1. Change the `CMD` of your Dockerfile to something like
```
CMD ./mvnw clean spring-boot:run -Dspring-boot.run.jvmArguments="-Dkeycloak.auth-server-url=http://keycloak:8080/auth"
```
P.S. Make sure you have curl and jq in this container.

2. Start docker-compose. It will start the services `keycloak`, `ldap-host`, `mysql-keycloak` and `phpldapadmin-service`. All running in the network `springboot-keycloak-openldap_default`.

3. Configure LDAP and Keycloak as I explained in the README

4. Start spring-boot application, joining it to the network `springboot-keycloak-openldap_default`
```
docker build -t springboot . && docker run -p $PORT:8080 --network=springboot-keycloak-openldap_default springboot
```

5. Docker exec into springboot and *get token from there*
```
docker exec -it springboot sh

> export SIMPLE_SERVICE_CLIENT_SECRET=...

> BGATES_ACCESS_TOKEN=$(curl -s -X POST \
  "http://keycloak:8080/auth/realms/company-services/protocol/openid-connect/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "username=bgates" \
  -d "password=123" \
  -d "grant_type=password" \
  -d "client_secret=$SIMPLE_SERVICE_CLIENT_SECRET" \
  -d "client_id=simple-service" | jq -r .access_token)

> echo $BGATES_ACCESS_TOKEN
```

6. Go back to host and run the curl informing the token got inside springboot container
```
curl -i -H "Authorization: Bearer $BGATES_ACCESS_TOKEN" http://localhost:8080/api/private
```

It should work. Unfortunately, I won't have time to try it today. Could you do, please? And let me know if it works. 

Best regards,

**Comment by ivangfr** [comment]
@mitni455 I've updated the project adding Dockerfile and a section on README explaining how to run the spring-boot application in a Docker container. Let me know if it is OK for you and then I will close the issue. Best regards,

**Comment by mightyhorst** [comment]
Wow thanks so much for the comprehensive answer! Yes this categorically fixed the issue, and provided a incredibly valuable understanding of the cause in the first place. Thank you kindly, yes this issue is resolved and can be closed.
